//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace LenovoLegionToolkit.Lib.Resources {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "18.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resource() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("LenovoLegionToolkit.Lib.Resources.Resource", typeof(Resource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   重写当前线程的 CurrentUICulture 属性，对
        ///   使用此强类型资源类的所有资源查找执行重写。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 Custom 的本地化字符串。
        /// </summary>
        public static string AccentColorSource_Custom {
            get {
                return ResourceManager.GetString("AccentColorSource_Custom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 System 的本地化字符串。
        /// </summary>
        public static string AccentColorSource_System {
            get {
                return ResourceManager.GetString("AccentColorSource_System", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Off 的本地化字符串。
        /// </summary>
        public static string AlwaysOnUSBState_Off {
            get {
                return ResourceManager.GetString("AlwaysOnUSBState_Off", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 On, always 的本地化字符串。
        /// </summary>
        public static string AlwaysOnUSBState_OnAlways {
            get {
                return ResourceManager.GetString("AlwaysOnUSBState_OnAlways", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 On, when sleeping 的本地化字符串。
        /// </summary>
        public static string AlwaysOnUSBState_OnWhenSleeping {
            get {
                return ResourceManager.GetString("AlwaysOnUSBState_OnWhenSleeping", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Profile will not apply without AC adapter (Full wattage) connected. 的本地化字符串。
        /// </summary>
        public static string AmdOverclocking_Ac_Message {
            get {
                return ResourceManager.GetString("AmdOverclocking_Ac_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Not initialized. 的本地化字符串。
        /// </summary>
        public static string AmdOverclocking_Not_Initialized_Message {
            get {
                return ResourceManager.GetString("AmdOverclocking_Not_Initialized_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Not supported. 的本地化字符串。
        /// </summary>
        public static string AmdOverclocking_Not_Supported {
            get {
                return ResourceManager.GetString("AmdOverclocking_Not_Supported", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Warning: For safety, these steps will be skipped on startup: {0}. All other steps will execute normally. 的本地化字符串。
        /// </summary>
        public static string Automation_Warning_Startup {
            get {
                return ResourceManager.GetString("Automation_Warning_Startup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Disabled 的本地化字符串。
        /// </summary>
        public static string AutorunState_Disabled {
            get {
                return ResourceManager.GetString("AutorunState_Disabled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Enabled 的本地化字符串。
        /// </summary>
        public static string AutorunState_Enabled {
            get {
                return ResourceManager.GetString("AutorunState_Enabled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Enabled (delayed) 的本地化字符串。
        /// </summary>
        public static string AutorunState_EnabledDelayed {
            get {
                return ResourceManager.GetString("AutorunState_EnabledDelayed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Balanced 的本地化字符串。
        /// </summary>
        public static string Balanced {
            get {
                return ResourceManager.GetString("Balanced", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Off 的本地化字符串。
        /// </summary>
        public static string BatteryNightChargeState_Off {
            get {
                return ResourceManager.GetString("BatteryNightChargeState_Off", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 On 的本地化字符串。
        /// </summary>
        public static string BatteryNightChargeState_On {
            get {
                return ResourceManager.GetString("BatteryNightChargeState_On", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Conservation 的本地化字符串。
        /// </summary>
        public static string BatteryState_Conservation {
            get {
                return ResourceManager.GetString("BatteryState_Conservation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Normal 的本地化字符串。
        /// </summary>
        public static string BatteryState_Normal {
            get {
                return ResourceManager.GetString("BatteryState_Normal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Rapid Charge 的本地化字符串。
        /// </summary>
        public static string BatteryState_RapidCharge {
            get {
                return ResourceManager.GetString("BatteryState_RapidCharge", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Best Performance 的本地化字符串。
        /// </summary>
        public static string BestPerformance {
            get {
                return ResourceManager.GetString("BestPerformance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Best Power Efficiency 的本地化字符串。
        /// </summary>
        public static string BestPowerEfficiency {
            get {
                return ResourceManager.GetString("BestPowerEfficiency", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 CPU Fan 的本地化字符串。
        /// </summary>
        public static string CustomFanCurveControl_Fan_CPU {
            get {
                return ResourceManager.GetString("CustomFanCurveControl_Fan_CPU", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 GPU Fan 的本地化字符串。
        /// </summary>
        public static string CustomFanCurveControl_Fan_GPU {
            get {
                return ResourceManager.GetString("CustomFanCurveControl_Fan_GPU", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 System Fan 的本地化字符串。
        /// </summary>
        public static string CustomFanCurveControl_Fan_System {
            get {
                return ResourceManager.GetString("CustomFanCurveControl_Fan_System", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Custom 的本地化字符串。
        /// </summary>
        public static string CustomSpecialKey_Custom {
            get {
                return ResourceManager.GetString("CustomSpecialKey_Custom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Default 的本地化字符串。
        /// </summary>
        public static string CustomSpecialKey_Default {
            get {
                return ResourceManager.GetString("CustomSpecialKey_Default", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Off 的本地化字符串。
        /// </summary>
        public static string FlipToStartState_Off {
            get {
                return ResourceManager.GetString("FlipToStartState_Off", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 On 的本地化字符串。
        /// </summary>
        public static string FlipToStartState_On {
            get {
                return ResourceManager.GetString("FlipToStartState_On", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Off 的本地化字符串。
        /// </summary>
        public static string FnLockState_Off {
            get {
                return ResourceManager.GetString("FnLockState_Off", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 On 的本地化字符串。
        /// </summary>
        public static string FnLockState_On {
            get {
                return ResourceManager.GetString("FnLockState_On", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 GB 的本地化字符串。
        /// </summary>
        public static string GB {
            get {
                return ResourceManager.GetString("GB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Powered Off 的本地化字符串。
        /// </summary>
        public static string GPUController_PoweredOff {
            get {
                return ResourceManager.GetString("GPUController_PoweredOff", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Powered On 的本地化字符串。
        /// </summary>
        public static string GPUController_PoweredOn {
            get {
                return ResourceManager.GetString("GPUController_PoweredOn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Off 的本地化字符串。
        /// </summary>
        public static string HardwareSensorsState_Off {
            get {
                return ResourceManager.GetString("HardwareSensorsState_Off", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 On 的本地化字符串。
        /// </summary>
        public static string HardwareSensorsState_On {
            get {
                return ResourceManager.GetString("HardwareSensorsState_On", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Off 的本地化字符串。
        /// </summary>
        public static string HDRState_Off {
            get {
                return ResourceManager.GetString("HDRState_Off", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 On 的本地化字符串。
        /// </summary>
        public static string HDRState_On {
            get {
                return ResourceManager.GetString("HDRState_On", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 dGPU 的本地化字符串。
        /// </summary>
        public static string HybridModeState_Off {
            get {
                return ResourceManager.GetString("HybridModeState_Off", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Hybrid 的本地化字符串。
        /// </summary>
        public static string HybridModeState_On {
            get {
                return ResourceManager.GetString("HybridModeState_On", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Hybrid-Auto 的本地化字符串。
        /// </summary>
        public static string HybridModeState_OnAuto {
            get {
                return ResourceManager.GetString("HybridModeState_OnAuto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Hybrid-iGPU 的本地化字符串。
        /// </summary>
        public static string HybridModeState_OnIGPUOnly {
            get {
                return ResourceManager.GetString("HybridModeState_OnIGPUOnly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 UMA 的本地化字符串。
        /// </summary>
        public static string HybridModeState_UMA {
            get {
                return ResourceManager.GetString("HybridModeState_UMA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 AC Adapter 的本地化字符串。
        /// </summary>
        public static string InstantBootState_AcAdapter {
            get {
                return ResourceManager.GetString("InstantBootState_AcAdapter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 AC and USB PD 的本地化字符串。
        /// </summary>
        public static string InstantBootState_AcAdapterAndUsbPowerDelivery {
            get {
                return ResourceManager.GetString("InstantBootState_AcAdapterAndUsbPowerDelivery", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Off 的本地化字符串。
        /// </summary>
        public static string InstantBootState_Off {
            get {
                return ResourceManager.GetString("InstantBootState_Off", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 USB Power Delivery 的本地化字符串。
        /// </summary>
        public static string InstantBootState_UsbPowerDelivery {
            get {
                return ResourceManager.GetString("InstantBootState_UsbPowerDelivery", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Battery Saving 的本地化字符串。
        /// </summary>
        public static string ITSMode_Intelligent_Battery_Saving {
            get {
                return ResourceManager.GetString("ITSMode_Intelligent_Battery_Saving", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Intelligent Cooling 的本地化字符串。
        /// </summary>
        public static string ITSMode_Intelligent_Cooling {
            get {
                return ResourceManager.GetString("ITSMode_Intelligent_Cooling", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Creator 的本地化字符串。
        /// </summary>
        public static string ITSMode_Intelligent_Creator {
            get {
                return ResourceManager.GetString("ITSMode_Intelligent_Creator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Extreme Performance 的本地化字符串。
        /// </summary>
        public static string ITSMode_Intelligent_Extreme_Performance {
            get {
                return ResourceManager.GetString("ITSMode_Intelligent_Extreme_Performance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Geek 的本地化字符串。
        /// </summary>
        public static string ITSMode_Intelligent_Geek {
            get {
                return ResourceManager.GetString("ITSMode_Intelligent_Geek", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Off 的本地化字符串。
        /// </summary>
        public static string MicrophoneState_Off {
            get {
                return ResourceManager.GetString("MicrophoneState_Off", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 On 的本地化字符串。
        /// </summary>
        public static string MicrophoneState_On {
            get {
                return ResourceManager.GetString("MicrophoneState_On", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Alt 的本地化字符串。
        /// </summary>
        public static string ModifierKey_Alt {
            get {
                return ResourceManager.GetString("ModifierKey_Alt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Ctrl 的本地化字符串。
        /// </summary>
        public static string ModifierKey_Ctrl {
            get {
                return ResourceManager.GetString("ModifierKey_Ctrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Shift 的本地化字符串。
        /// </summary>
        public static string ModifierKey_Shift {
            get {
                return ResourceManager.GetString("ModifierKey_Shift", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Long 的本地化字符串。
        /// </summary>
        public static string NotificationDuration_Long {
            get {
                return ResourceManager.GetString("NotificationDuration_Long", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Normal 的本地化字符串。
        /// </summary>
        public static string NotificationDuration_Normal {
            get {
                return ResourceManager.GetString("NotificationDuration_Normal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Short 的本地化字符串。
        /// </summary>
        public static string NotificationDuration_Short {
            get {
                return ResourceManager.GetString("NotificationDuration_Short", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Bottom center 的本地化字符串。
        /// </summary>
        public static string NotificationPosition_BottomCenter {
            get {
                return ResourceManager.GetString("NotificationPosition_BottomCenter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Bottom left 的本地化字符串。
        /// </summary>
        public static string NotificationPosition_BottomLeft {
            get {
                return ResourceManager.GetString("NotificationPosition_BottomLeft", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Bottom right 的本地化字符串。
        /// </summary>
        public static string NotificationPosition_BottomRight {
            get {
                return ResourceManager.GetString("NotificationPosition_BottomRight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Center 的本地化字符串。
        /// </summary>
        public static string NotificationPosition_Center {
            get {
                return ResourceManager.GetString("NotificationPosition_Center", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Center left 的本地化字符串。
        /// </summary>
        public static string NotificationPosition_CenterLeft {
            get {
                return ResourceManager.GetString("NotificationPosition_CenterLeft", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Center right 的本地化字符串。
        /// </summary>
        public static string NotificationPosition_CenterRight {
            get {
                return ResourceManager.GetString("NotificationPosition_CenterRight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Top center 的本地化字符串。
        /// </summary>
        public static string NotificationPosition_TopCenter {
            get {
                return ResourceManager.GetString("NotificationPosition_TopCenter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Top left 的本地化字符串。
        /// </summary>
        public static string NotificationPosition_TopLeft {
            get {
                return ResourceManager.GetString("NotificationPosition_TopLeft", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Top right 的本地化字符串。
        /// </summary>
        public static string NotificationPosition_TopRight {
            get {
                return ResourceManager.GetString("NotificationPosition_TopRight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Off 的本地化字符串。
        /// </summary>
        public static string OneLevelWhiteKeyboardBacklightState_Off {
            get {
                return ResourceManager.GetString("OneLevelWhiteKeyboardBacklightState_Off", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 On 的本地化字符串。
        /// </summary>
        public static string OneLevelWhiteKeyboardBacklightState_On {
            get {
                return ResourceManager.GetString("OneLevelWhiteKeyboardBacklightState_On", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Disk 1 Temperature 的本地化字符串。
        /// </summary>
        public static string OsdItem_Disk1Temperature {
            get {
                return ResourceManager.GetString("OsdItem_Disk1Temperature", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Disk 2 Temperature 的本地化字符串。
        /// </summary>
        public static string OsdItem_Disk2Temperature {
            get {
                return ResourceManager.GetString("OsdItem_Disk2Temperature", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 E-Core Clock 的本地化字符串。
        /// </summary>
        public static string OsdItem_E_Core_Frequency {
            get {
                return ResourceManager.GetString("OsdItem_E_Core_Frequency", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Fan 的本地化字符串。
        /// </summary>
        public static string OsdItem_Fan {
            get {
                return ResourceManager.GetString("OsdItem_Fan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 FPS 的本地化字符串。
        /// </summary>
        public static string OsdItem_Fps {
            get {
                return ResourceManager.GetString("OsdItem_Fps", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Frame Time 的本地化字符串。
        /// </summary>
        public static string OsdItem_FrameTime {
            get {
                return ResourceManager.GetString("OsdItem_FrameTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Frequency 的本地化字符串。
        /// </summary>
        public static string OsdItem_Frequency {
            get {
                return ResourceManager.GetString("OsdItem_Frequency", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 1% Low 的本地化字符串。
        /// </summary>
        public static string OsdItem_LowFps {
            get {
                return ResourceManager.GetString("OsdItem_LowFps", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Memory Temperature 的本地化字符串。
        /// </summary>
        public static string OsdItem_MemoryTemperature {
            get {
                return ResourceManager.GetString("OsdItem_MemoryTemperature", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Motherboard Temperature 的本地化字符串。
        /// </summary>
        public static string OsdItem_MotherboardTemperature {
            get {
                return ResourceManager.GetString("OsdItem_MotherboardTemperature", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 P-Core Clock 的本地化字符串。
        /// </summary>
        public static string OsdItem_P_Core_Frequency {
            get {
                return ResourceManager.GetString("OsdItem_P_Core_Frequency", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Power 的本地化字符串。
        /// </summary>
        public static string OsdItem_Power {
            get {
                return ResourceManager.GetString("OsdItem_Power", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Temperature 的本地化字符串。
        /// </summary>
        public static string OsdItem_Temperature {
            get {
                return ResourceManager.GetString("OsdItem_Temperature", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Utilization 的本地化字符串。
        /// </summary>
        public static string OsdItem_Utilization {
            get {
                return ResourceManager.GetString("OsdItem_Utilization", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 VRAM Temperature 的本地化字符串。
        /// </summary>
        public static string OsdItem_VramTemperature {
            get {
                return ResourceManager.GetString("OsdItem_VramTemperature", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 VRAM Utilization 的本地化字符串。
        /// </summary>
        public static string OsdItem_VramUtilization {
            get {
                return ResourceManager.GetString("OsdItem_VramUtilization", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Off 的本地化字符串。
        /// </summary>
        public static string OverdriveState_Off {
            get {
                return ResourceManager.GetString("OverdriveState_Off", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 On 的本地化字符串。
        /// </summary>
        public static string OverdriveState_On {
            get {
                return ResourceManager.GetString("OverdriveState_On", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Off 的本地化字符串。
        /// </summary>
        public static string PanelLogoBacklightState_Off {
            get {
                return ResourceManager.GetString("PanelLogoBacklightState_Off", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 On 的本地化字符串。
        /// </summary>
        public static string PanelLogoBacklightState_On {
            get {
                return ResourceManager.GetString("PanelLogoBacklightState_On", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Off 的本地化字符串。
        /// </summary>
        public static string PortsBacklightState_Off {
            get {
                return ResourceManager.GetString("PortsBacklightState_Off", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 On 的本地化字符串。
        /// </summary>
        public static string PortsBacklightState_On {
            get {
                return ResourceManager.GetString("PortsBacklightState_On", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Disabled 的本地化字符串。
        /// </summary>
        public static string PowerModeMappingMode_Disabled {
            get {
                return ResourceManager.GetString("PowerModeMappingMode_Disabled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Windows Power Mode 的本地化字符串。
        /// </summary>
        public static string PowerModeMappingMode_WindowsPowerMode {
            get {
                return ResourceManager.GetString("PowerModeMappingMode_WindowsPowerMode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Windows Power Plan 的本地化字符串。
        /// </summary>
        public static string PowerModeMappingMode_WindowsPowerPlan {
            get {
                return ResourceManager.GetString("PowerModeMappingMode_WindowsPowerPlan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Balance 的本地化字符串。
        /// </summary>
        public static string PowerModeState_Balance {
            get {
                return ResourceManager.GetString("PowerModeState_Balance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Extreme 的本地化字符串。
        /// </summary>
        public static string PowerModeState_Extreme {
            get {
                return ResourceManager.GetString("PowerModeState_Extreme", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Custom 的本地化字符串。
        /// </summary>
        public static string PowerModeState_GodMode {
            get {
                return ResourceManager.GetString("PowerModeState_GodMode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Performance 的本地化字符串。
        /// </summary>
        public static string PowerModeState_Performance {
            get {
                return ResourceManager.GetString("PowerModeState_Performance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Quiet 的本地化字符串。
        /// </summary>
        public static string PowerModeState_Quiet {
            get {
                return ResourceManager.GetString("PowerModeState_Quiet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 High 的本地化字符串。
        /// </summary>
        public static string RGBKeyboardBacklightBrightness_High {
            get {
                return ResourceManager.GetString("RGBKeyboardBacklightBrightness_High", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Low 的本地化字符串。
        /// </summary>
        public static string RGBKeyboardBacklightBrightness_Low {
            get {
                return ResourceManager.GetString("RGBKeyboardBacklightBrightness_Low", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Breath 的本地化字符串。
        /// </summary>
        public static string RGBKeyboardBacklightEffect_Breath {
            get {
                return ResourceManager.GetString("RGBKeyboardBacklightEffect_Breath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Smooth 的本地化字符串。
        /// </summary>
        public static string RGBKeyboardBacklightEffect_Smooth {
            get {
                return ResourceManager.GetString("RGBKeyboardBacklightEffect_Smooth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Static 的本地化字符串。
        /// </summary>
        public static string RGBKeyboardBacklightEffect_Static {
            get {
                return ResourceManager.GetString("RGBKeyboardBacklightEffect_Static", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Wave Left 的本地化字符串。
        /// </summary>
        public static string RGBKeyboardBacklightEffect_WaveLTR {
            get {
                return ResourceManager.GetString("RGBKeyboardBacklightEffect_WaveLTR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Wave Right 的本地化字符串。
        /// </summary>
        public static string RGBKeyboardBacklightEffect_WaveRTL {
            get {
                return ResourceManager.GetString("RGBKeyboardBacklightEffect_WaveRTL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Preset 4 的本地化字符串。
        /// </summary>
        public static string RGBKeyboardBacklightPreset_Four {
            get {
                return ResourceManager.GetString("RGBKeyboardBacklightPreset_Four", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Off 的本地化字符串。
        /// </summary>
        public static string RGBKeyboardBacklightPreset_Off {
            get {
                return ResourceManager.GetString("RGBKeyboardBacklightPreset_Off", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Preset 1 的本地化字符串。
        /// </summary>
        public static string RGBKeyboardBacklightPreset_One {
            get {
                return ResourceManager.GetString("RGBKeyboardBacklightPreset_One", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Preset 3 的本地化字符串。
        /// </summary>
        public static string RGBKeyboardBacklightPreset_Three {
            get {
                return ResourceManager.GetString("RGBKeyboardBacklightPreset_Three", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Preset 2 的本地化字符串。
        /// </summary>
        public static string RGBKeyboardBacklightPreset_Two {
            get {
                return ResourceManager.GetString("RGBKeyboardBacklightPreset_Two", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Fast 的本地化字符串。
        /// </summary>
        public static string RGBKeyboardBacklightSpeed_Fast {
            get {
                return ResourceManager.GetString("RGBKeyboardBacklightSpeed_Fast", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Fastest 的本地化字符串。
        /// </summary>
        public static string RGBKeyboardBacklightSpeed_Fastest {
            get {
                return ResourceManager.GetString("RGBKeyboardBacklightSpeed_Fastest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Slow 的本地化字符串。
        /// </summary>
        public static string RGBKeyboardBacklightSpeed_Slow {
            get {
                return ResourceManager.GetString("RGBKeyboardBacklightSpeed_Slow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Slowest 的本地化字符串。
        /// </summary>
        public static string RGBKeyboardBacklightSpeed_Slowest {
            get {
                return ResourceManager.GetString("RGBKeyboardBacklightSpeed_Slowest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Shared / Dynamic 的本地化字符串。
        /// </summary>
        public static string SharedMemory {
            get {
                return ResourceManager.GetString("SharedMemory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Mute 的本地化字符串。
        /// </summary>
        public static string SpeakerState_Mute {
            get {
                return ResourceManager.GetString("SpeakerState_Mute", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Unmute 的本地化字符串。
        /// </summary>
        public static string SpeakerState_Unmute {
            get {
                return ResourceManager.GetString("SpeakerState_Unmute", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 High 的本地化字符串。
        /// </summary>
        public static string SpectrumKeyboardBacklightBrightness_High {
            get {
                return ResourceManager.GetString("SpectrumKeyboardBacklightBrightness_High", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Low 的本地化字符串。
        /// </summary>
        public static string SpectrumKeyboardBacklightBrightness_Low {
            get {
                return ResourceManager.GetString("SpectrumKeyboardBacklightBrightness_Low", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Medium 的本地化字符串。
        /// </summary>
        public static string SpectrumKeyboardBacklightBrightness_Medium {
            get {
                return ResourceManager.GetString("SpectrumKeyboardBacklightBrightness_Medium", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Off 的本地化字符串。
        /// </summary>
        public static string SpectrumKeyboardBacklightBrightness_Off {
            get {
                return ResourceManager.GetString("SpectrumKeyboardBacklightBrightness_Off", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Bottom to Top 的本地化字符串。
        /// </summary>
        public static string SpectrumKeyboardBacklightDirection_BottomToTop {
            get {
                return ResourceManager.GetString("SpectrumKeyboardBacklightDirection_BottomToTop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Clockwise 的本地化字符串。
        /// </summary>
        public static string SpectrumKeyboardBacklightDirection_Clockwise {
            get {
                return ResourceManager.GetString("SpectrumKeyboardBacklightDirection_Clockwise", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Counter Clockwise 的本地化字符串。
        /// </summary>
        public static string SpectrumKeyboardBacklightDirection_CounterClockwise {
            get {
                return ResourceManager.GetString("SpectrumKeyboardBacklightDirection_CounterClockwise", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Left to Right 的本地化字符串。
        /// </summary>
        public static string SpectrumKeyboardBacklightDirection_LeftToRight {
            get {
                return ResourceManager.GetString("SpectrumKeyboardBacklightDirection_LeftToRight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Right to Left 的本地化字符串。
        /// </summary>
        public static string SpectrumKeyboardBacklightDirection_RightToLeft {
            get {
                return ResourceManager.GetString("SpectrumKeyboardBacklightDirection_RightToLeft", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Top to Bottom 的本地化字符串。
        /// </summary>
        public static string SpectrumKeyboardBacklightDirection_TopToBottom {
            get {
                return ResourceManager.GetString("SpectrumKeyboardBacklightDirection_TopToBottom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Always 的本地化字符串。
        /// </summary>
        public static string SpectrumKeyboardBacklightEffectType_Always {
            get {
                return ResourceManager.GetString("SpectrumKeyboardBacklightEffectType_Always", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Audio Bounce 的本地化字符串。
        /// </summary>
        public static string SpectrumKeyboardBacklightEffectType_AudioBounce {
            get {
                return ResourceManager.GetString("SpectrumKeyboardBacklightEffectType_AudioBounce", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Audio Ripple 的本地化字符串。
        /// </summary>
        public static string SpectrumKeyboardBacklightEffectType_AudioRipple {
            get {
                return ResourceManager.GetString("SpectrumKeyboardBacklightEffectType_AudioRipple", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Aurora Sync 的本地化字符串。
        /// </summary>
        public static string SpectrumKeyboardBacklightEffectType_AuroraSync {
            get {
                return ResourceManager.GetString("SpectrumKeyboardBacklightEffectType_AuroraSync", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Color Change 的本地化字符串。
        /// </summary>
        public static string SpectrumKeyboardBacklightEffectType_ColorChange {
            get {
                return ResourceManager.GetString("SpectrumKeyboardBacklightEffectType_ColorChange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Color Pulse 的本地化字符串。
        /// </summary>
        public static string SpectrumKeyboardBacklightEffectType_ColorPulse {
            get {
                return ResourceManager.GetString("SpectrumKeyboardBacklightEffectType_ColorPulse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Color Wave 的本地化字符串。
        /// </summary>
        public static string SpectrumKeyboardBacklightEffectType_ColorWave {
            get {
                return ResourceManager.GetString("SpectrumKeyboardBacklightEffectType_ColorWave", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Rain 的本地化字符串。
        /// </summary>
        public static string SpectrumKeyboardBacklightEffectType_Rain {
            get {
                return ResourceManager.GetString("SpectrumKeyboardBacklightEffectType_Rain", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Rainbow Screw 的本地化字符串。
        /// </summary>
        public static string SpectrumKeyboardBacklightEffectType_RainbowScrew {
            get {
                return ResourceManager.GetString("SpectrumKeyboardBacklightEffectType_RainbowScrew", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Rainbow Wave 的本地化字符串。
        /// </summary>
        public static string SpectrumKeyboardBacklightEffectType_RainbowWave {
            get {
                return ResourceManager.GetString("SpectrumKeyboardBacklightEffectType_RainbowWave", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Ripple 的本地化字符串。
        /// </summary>
        public static string SpectrumKeyboardBacklightEffectType_Ripple {
            get {
                return ResourceManager.GetString("SpectrumKeyboardBacklightEffectType_Ripple", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Smooth 的本地化字符串。
        /// </summary>
        public static string SpectrumKeyboardBacklightEffectType_Smooth {
            get {
                return ResourceManager.GetString("SpectrumKeyboardBacklightEffectType_Smooth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Type 的本地化字符串。
        /// </summary>
        public static string SpectrumKeyboardBacklightEffectType_Type {
            get {
                return ResourceManager.GetString("SpectrumKeyboardBacklightEffectType_Type", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Slow 的本地化字符串。
        /// </summary>
        public static string SpectrumKeyboardBacklightSpeed_Speed1 {
            get {
                return ResourceManager.GetString("SpectrumKeyboardBacklightSpeed_Speed1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Medium 的本地化字符串。
        /// </summary>
        public static string SpectrumKeyboardBacklightSpeed_Speed2 {
            get {
                return ResourceManager.GetString("SpectrumKeyboardBacklightSpeed_Speed2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Fast 的本地化字符串。
        /// </summary>
        public static string SpectrumKeyboardBacklightSpeed_Speed3 {
            get {
                return ResourceManager.GetString("SpectrumKeyboardBacklightSpeed_Speed3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Dark 的本地化字符串。
        /// </summary>
        public static string Theme_Dark {
            get {
                return ResourceManager.GetString("Theme_Dark", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Light 的本地化字符串。
        /// </summary>
        public static string Theme_Light {
            get {
                return ResourceManager.GetString("Theme_Light", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 System 的本地化字符串。
        /// </summary>
        public static string Theme_System {
            get {
                return ResourceManager.GetString("Theme_System", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Off 的本地化字符串。
        /// </summary>
        public static string ToggleState_Off {
            get {
                return ResourceManager.GetString("ToggleState_Off", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 On 的本地化字符串。
        /// </summary>
        public static string ToggleState_On {
            get {
                return ResourceManager.GetString("ToggleState_On", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Toggle 的本地化字符串。
        /// </summary>
        public static string ToggleState_Toggle {
            get {
                return ResourceManager.GetString("ToggleState_Toggle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Off 的本地化字符串。
        /// </summary>
        public static string TouchpadLockState_Off {
            get {
                return ResourceManager.GetString("TouchpadLockState_Off", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 On 的本地化字符串。
        /// </summary>
        public static string TouchpadLockState_On {
            get {
                return ResourceManager.GetString("TouchpadLockState_On", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Beta 的本地化字符串。
        /// </summary>
        public static string UpdateChannel_Beta {
            get {
                return ResourceManager.GetString("UpdateChannel_Beta", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Dev 的本地化字符串。
        /// </summary>
        public static string UpdateChannel_Dev {
            get {
                return ResourceManager.GetString("UpdateChannel_Dev", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Stable 的本地化字符串。
        /// </summary>
        public static string UpdateChannel_Stable {
            get {
                return ResourceManager.GetString("UpdateChannel_Stable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Test 的本地化字符串。
        /// </summary>
        public static string UpdateChannel_Test {
            get {
                return ResourceManager.GetString("UpdateChannel_Test", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The downloaded update is not signed by the trusted server certificate {0} 的本地化字符串。
        /// </summary>
        public static string UpdateChecker_Security_Invalid {
            get {
                return ResourceManager.GetString("UpdateChecker_Security_Invalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Invalid signature thumbprint {0} 的本地化字符串。
        /// </summary>
        public static string UpdateChecker_Security_Thumbprint {
            get {
                return ResourceManager.GetString("UpdateChecker_Security_Thumbprint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Never 的本地化字符串。
        /// </summary>
        public static string UpdateCheckFrequency_Never {
            get {
                return ResourceManager.GetString("UpdateCheckFrequency_Never", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Daily 的本地化字符串。
        /// </summary>
        public static string UpdateCheckFrequency_PerDay {
            get {
                return ResourceManager.GetString("UpdateCheckFrequency_PerDay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Every hour 的本地化字符串。
        /// </summary>
        public static string UpdateCheckFrequency_PerHour {
            get {
                return ResourceManager.GetString("UpdateCheckFrequency_PerHour", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Monthly 的本地化字符串。
        /// </summary>
        public static string UpdateCheckFrequency_PerMonth {
            get {
                return ResourceManager.GetString("UpdateCheckFrequency_PerMonth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Every 3 hours 的本地化字符串。
        /// </summary>
        public static string UpdateCheckFrequency_PerThreeHours {
            get {
                return ResourceManager.GetString("UpdateCheckFrequency_PerThreeHours", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Every 12 hours 的本地化字符串。
        /// </summary>
        public static string UpdateCheckFrequency_PerTwelveHours {
            get {
                return ResourceManager.GetString("UpdateCheckFrequency_PerTwelveHours", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Weekly 的本地化字符串。
        /// </summary>
        public static string UpdateCheckFrequency_PerWeek {
            get {
                return ResourceManager.GetString("UpdateCheckFrequency_PerWeek", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 GitHub 的本地化字符串。
        /// </summary>
        public static string UpdateMethod_GitHub {
            get {
                return ResourceManager.GetString("UpdateMethod_GitHub", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Server 的本地化字符串。
        /// </summary>
        public static string UpdateMethod_Server {
            get {
                return ResourceManager.GetString("UpdateMethod_Server", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 High 的本地化字符串。
        /// </summary>
        public static string WhiteKeyboardBacklightState_High {
            get {
                return ResourceManager.GetString("WhiteKeyboardBacklightState_High", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Low 的本地化字符串。
        /// </summary>
        public static string WhiteKeyboardBacklightState_Low {
            get {
                return ResourceManager.GetString("WhiteKeyboardBacklightState_Low", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Off 的本地化字符串。
        /// </summary>
        public static string WhiteKeyboardBacklightState_Off {
            get {
                return ResourceManager.GetString("WhiteKeyboardBacklightState_Off", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Acrylic 的本地化字符串。
        /// </summary>
        public static string WindowBackdropType_Acrylic {
            get {
                return ResourceManager.GetString("WindowBackdropType_Acrylic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Mica 的本地化字符串。
        /// </summary>
        public static string WindowBackdropType_Mica {
            get {
                return ResourceManager.GetString("WindowBackdropType_Mica", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 None 的本地化字符串。
        /// </summary>
        public static string WindowBackdropType_None {
            get {
                return ResourceManager.GetString("WindowBackdropType_None", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Tabbed 的本地化字符串。
        /// </summary>
        public static string WindowBackdropType_Tabbed {
            get {
                return ResourceManager.GetString("WindowBackdropType_Tabbed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Off 的本地化字符串。
        /// </summary>
        public static string WinKeyState_Off {
            get {
                return ResourceManager.GetString("WinKeyState_Off", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 On 的本地化字符串。
        /// </summary>
        public static string WinKeyState_On {
            get {
                return ResourceManager.GetString("WinKeyState_On", resourceCulture);
            }
        }
    }
}
